### ISSUE TITLE
Setting environment doesnt work on windows

### ISSUE THREAD

**Issue by oba11** [jonhadfield/sts#2]
Hi,

Tried running the below command on a windows 10 laptop but doesn't seem to work
```
sts.exe get-session-token --serial-number arn:aws:iam::123456789012:mfa/user --token-code 123456 -s
```

Thanks

**Comment by jonhadfield** [comment]
Hi @oba11, thanks for reporting this.
It seems the call made to create a new shell with the environment variables set doesn't work in Windows, only Linux and MacOS.
I'll see if there's a different way of doing this in Windows, an alternative, or if I have to remove the option in the Windows build.

**Comment by jonhadfield** [comment]
I've just released a [new version](https://github.com/jonhadfield/sts/releases/tag/1.1.2) to add support for setting environment variables in Windows. It works by calling PowerShell so I'm hoping that's what Windows users will be on!
Let me know if you have any issues.

**Comment by oba11** [comment]
Awesome, thanks so much for this!
