### ISSUE TITLE
Not require MFA?

### ISSUE THREAD

**Issue by nhoughto** [jonhadfield/sts#5]
Almost super useful little CLI app, I just wanted to assume-role from a statically linked app to a normal role without the need for MFA, forcing it makes it impossible to use 😢

**Comment by jonhadfield** [comment]
Hi @nhoughto, you should be able to just hit enter when prompted for MFA if it's not required.
It's mentioned in the README under the known issues.

**Comment by nhoughto** [comment]
In my use case it’s a lambda execution calling the cli, so headless call with no opportunity to press enter =)

**Comment by jonhadfield** [comment]
Ah, have you tried specifying --token-code="" _(not tried it myself)_
If that doesn't work, I might be able to add a --no-mfa option. Just let me know.

Edit: I suspect that option won't work. It'll be seen as 'not provided'. I'll take a look to see if it's an easy change/fix to add a new option.

**Comment by nhoughto** [comment]
i was just looking at the code and i saw,

```
cli.BoolFlag{
					Name:  "no-mfa",
					Usage: "Assume role without MFA",
				},
```

then i saw commit 15 mins ago =) thanks!

**Comment by jonhadfield** [comment]
Just waiting for travis to finish the job that deploys the release to Github. You should see 1.1.3, with the new option, appear in releases in the next 10-20 mins.

**Comment by jonhadfield** [comment]
@nhoughto Had some problems with travis but finally got a [release](https://github.com/jonhadfield/sts/releases/tag/1.1.4) out.  
Please shout if there are any issues.
